volumes:
  postgres_data:

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data